[MAIN]
PERCENTILE=INC
INTERVAL=5
DATEFORMAT=MM/DD/YYYY
STANDBY=0.1
DATA_DIR=data
PERCENT_GROWTH=5
NUM_OF_YEAR=5
REFERENCE_CORE=82
[APOLLO] # Machine
APP_POOL1=LPAR1,LPAR3 #POOL = LPAR1,...
DB_POOL1=LPAR5
; [ARTEMIS]
; APP_POOL2=LPAR2,LPAR4
; DB_POOL2=LPAR6