[MAIN]
PERCENTILE=INC
INTERVAL=5
DATEFORMAT=MM/DD/YYYY
STANDBY=0.1
ANNUALIZATION_DAYS=365
DATA_DIR=data
BASE_PLANNING_GROWTH=5
CPU_UTILIZATION_GROWTH=5
CAPACITY_PLANNING_YEARS=3
CPU_UTILIZATION_YEARS=5
REFERENCE_CORE=52
[APOLLO] # Machine
APP_POOL1=LPAR1,LPAR3 #POOL = LPAR1,...
DB_POOL1=LPAR5
; [ARTEMIS]
; APP_POOL2=LPAR2,LPAR4
; DB_POOL2=LPAR6